[build]
  command = "pip install -r requirements.txt"
  publish = "src"

[functions]
  external_node_modules = [] # Fix for some build quirks, empty is fine

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
