[build]
  command = "pip install -r requirements.txt"
  publish = "src"

[functions]
  directory = "."
  included_files = ["data/**", "rewind.py"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main"
  status = 200
  force = true