[project]
name = "anilist-wrapped"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "httpx>=0.28.1",
    "python-dateutil>=2.9.0.post0",
    "uvicorn>=0.40.0",
]
